// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rovaya.DAL.Data;

#nullable disable

namespace Rovaya.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260921164554_medicalProfile")]
    partial class medicalProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rovaya.DAL.Models.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("EmergencyNumbers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.Identity.UserMedicalProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Allergies")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChronicDiseases")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CurrentMedications")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("UserMedicalProfiles");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.CitySection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImagesJson")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideosJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("CitySections");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuideCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TourismGuideCategories");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuideCategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TourismGuideCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TourismGuideCategoryId");

                    b.ToTable("TourismGuideCategoryTranslations");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("ParentPlaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentPlaceId");

                    b.ToTable("TourismGuidePlaces");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlaceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TourismGuidePlaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TourismGuidePlaceId");

                    b.ToTable("TourismGuidePlaceTranslations");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.Identity.UserMedicalProfile", b =>
                {
                    b.HasOne("Rovaya.DAL.Models.Auth.ApplicationUser", "ApplicationUser")
                        .WithOne("MedicalProfile")
                        .HasForeignKey("Rovaya.DAL.Models.Identity.UserMedicalProfile", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.CitySection", b =>
                {
                    b.HasOne("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuideCategoryTranslation", b =>
                {
                    b.HasOne("Rovaya.DAL.Models.TourismGuide.TourismGuideCategory", "TourismGuideCategory")
                        .WithMany("TourismGuideTranslations")
                        .HasForeignKey("TourismGuideCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourismGuideCategory");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", b =>
                {
                    b.HasOne("Rovaya.DAL.Models.TourismGuide.TourismGuideCategory", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", "ParentPlace")
                        .WithMany("SubPlaces")
                        .HasForeignKey("ParentPlaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("ParentPlace");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlaceTranslation", b =>
                {
                    b.HasOne("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", "TourismGuidePlace")
                        .WithMany("Translations")
                        .HasForeignKey("TourismGuidePlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourismGuidePlace");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.Auth.ApplicationUser", b =>
                {
                    b.Navigation("MedicalProfile");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuideCategory", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("TourismGuideTranslations");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", b =>
                {
                    b.Navigation("SubPlaces");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
