// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rovaya.DAL.Data;

#nullable disable

namespace Rovaya.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260917141522_Tour")]
    partial class Tour
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuideCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TourismGuideCategories");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuideCategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TourismGuideTranslations");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("ParentPlaceId")
                        .HasColumnType("integer");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ParentPlaceId");

                    b.ToTable("TourismGuidePlace");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlaceTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GeneralDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HighlightsAndAttractions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("TourismGuidePlaceTranslation");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuideCategoryTranslation", b =>
                {
                    b.HasOne("Rovaya.DAL.Models.TourismGuide.TourismGuideCategory", "Category")
                        .WithMany("TourismGuideTranslations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", b =>
                {
                    b.HasOne("Rovaya.DAL.Models.TourismGuide.TourismGuideCategory", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", "ParentPlace")
                        .WithMany("SubPlaces")
                        .HasForeignKey("ParentPlaceId");

                    b.Navigation("Category");

                    b.Navigation("ParentPlace");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlaceTranslation", b =>
                {
                    b.HasOne("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", "Place")
                        .WithMany("Translations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuideCategory", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("TourismGuideTranslations");
                });

            modelBuilder.Entity("Rovaya.DAL.Models.TourismGuide.TourismGuidePlace", b =>
                {
                    b.Navigation("SubPlaces");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
